// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiXcxg-Sm23fHu9hum9Iz5ooPbhdcAOdk',
    appId: '1:318957408891:web:3ba43f6d5726553568c8de',
    messagingSenderId: '318957408891',
    projectId: 'moto-pattaya',
    authDomain: 'moto-pattaya.firebaseapp.com',
    storageBucket: 'moto-pattaya.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4b591ytXuNM3FythaY8WjX5YtO6h1MpI',
    appId: '1:318957408891:android:ed7470a98fa5f22368c8de',
    messagingSenderId: '318957408891',
    projectId: 'moto-pattaya',
    storageBucket: 'moto-pattaya.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvAGRMnNLW7vlzEold-o9IU_ujp2hmfbE',
    appId: '1:318957408891:ios:4b57d45a1572932068c8de',
    messagingSenderId: '318957408891',
    projectId: 'moto-pattaya',
    storageBucket: 'moto-pattaya.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvAGRMnNLW7vlzEold-o9IU_ujp2hmfbE',
    appId: '1:318957408891:ios:12be665656c1b80568c8de',
    messagingSenderId: '318957408891',
    projectId: 'moto-pattaya',
    storageBucket: 'moto-pattaya.appspot.com',
    iosBundleId: 'com.example.auth.RunnerTests',
  );
}
